"""digest runs table

Revision ID: 0a6d64770772
Revises: c888c2c6e6c3
Create Date: 2026-07-09 15:36:11.543647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a6d64770772'
down_revision: Union[str, None] = 'c888c2c6e6c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digest_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('digest_runs')
    # ### end Alembic commands ###
