"""client confirmation basis

Revision ID: 8a11049f52b7
Revises: 0a6d64770772
Create Date: 2026-07-09 20:45:07.658340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a11049f52b7'
down_revision: Union[str, None] = '0a6d64770772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('confirmation_basis', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'confirmation_basis')
    # ### end Alembic commands ###
