"""proposal workflow columns

Revision ID: c888c2c6e6c3
Revises: 3d0a2d931cda
Create Date: 2026-07-09 15:17:48.844899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c888c2c6e6c3'
down_revision: Union[str, None] = '3d0a2d931cda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposals', sa.Column('requested_by', sa.UUID(), nullable=True))
    op.add_column('proposals', sa.Column('signatory_id', sa.UUID(), nullable=True))
    op.add_column('proposals', sa.Column('client_id', sa.UUID(), nullable=True))
    op.add_column('proposals', sa.Column('draft', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False))
    op.add_column('proposals', sa.Column('signatures', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False))
    op.add_column('proposals', sa.Column('revision_note', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('proposals', sa.Column('senior_note', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('proposals', sa.Column('proposal_sent_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.create_foreign_key(None, 'proposals', 'users', ['signatory_id'], ['id'])
    op.create_foreign_key(None, 'proposals', 'users', ['requested_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proposals', type_='foreignkey')
    op.drop_constraint(None, 'proposals', type_='foreignkey')
    op.drop_column('proposals', 'proposal_sent_at')
    op.drop_column('proposals', 'senior_note')
    op.drop_column('proposals', 'revision_note')
    op.drop_column('proposals', 'signatures')
    op.drop_column('proposals', 'draft')
    op.drop_column('proposals', 'client_id')
    op.drop_column('proposals', 'signatory_id')
    op.drop_column('proposals', 'requested_by')
    # ### end Alembic commands ###
