"""payment invoice proof

Revision ID: db72df01e5c1
Revises: ebbe1ad6aee0
Create Date: 2026-07-10 00:17:25.397368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db72df01e5c1'
down_revision: Union[str, None] = 'ebbe1ad6aee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('invoice_raised_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('payments', sa.Column('invoice', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'invoice')
    op.drop_column('payments', 'invoice_raised_at')
    # ### end Alembic commands ###
